version: '3'
services:
  # server:
  #   build: .
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db
  #   links:
  #     - db
  #   restart: always
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  db:
    image: postgres:alpine3.16
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:${POSTGRES_PORT}"
    restart: always